---
output:
  pdf_document: default
  html_document: default
---
#  Graphical Descriptions of Antibody Marker Data {#ab-grapical}

```{r, echo=FALSE, message=FALSE}
message("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ running cor_graphical report ~~~~~~~~~~~~~~~~~~~~~~~~~~~~")
```


```{r, echo=FALSE, results='asis'}
library(renv)
library(here)
library(knitr)
library(latex2exp)
here::i_am("cor_graphical/report.Rmd")

if(study_name=="COVEBoost"){
  set1_panels_1 = c("pseudoneutid50","bindSpike")
  set1_panels_2 = c("bindSpike")
  set1_times <- c("BD1","BD29","DeltaBD29overBD1")
  
  set2_panels = c("pseudoneutid50","bindSpike")
  
  set3_times = c("BD1","BD29","DeltaBD29overBD1")
  
}
    
## Set 1: violin and line plots #############
for (strain in c("2_strain")){
  for (panel in set1_panels_1) {
    for (time in set1_times) {
  
        res = knitr::knit_child(c(here::here('cor_graphical', 'report_sub1.Rmd')), quiet = TRUE)
        cat(res, sep = '\n')
        cat("\\clearpage", sep = '\n')
    }
  }
}
for (strain in c("2_strain")){
  for (panel in set1_panels_1) {
    for (time in set1_times) {
  
        res = knitr::knit_child(c(here::here('cor_graphical', 'report_sub1.2.Rmd')), quiet = TRUE)
        cat(res, sep = '\n')
        cat("\\clearpage", sep = '\n')
    }
  }
}
for (strain in c("2_strain")){
  for (panel in set1_panels_1) {
    for (time in set1_times) {
  
        res = knitr::knit_child(c(here::here('cor_graphical', 'report_sub1.3.Rmd')), quiet = TRUE)
        cat(res, sep = '\n')
        cat("\\clearpage", sep = '\n')
    }
  }
}
for (strain in c("6_strain")){
  for (panel in set1_panels_2) {
    for (time in set1_times) {
  
        res = knitr::knit_child(c(here::here('cor_graphical', 'report_sub1.Rmd')), quiet = TRUE)
        cat(res, sep = '\n')
        cat("\\clearpage", sep = '\n')
    }
  }
}
for (strain in c("6_strain")){
  for (panel in set1_panels_2) {
    for (time in set1_times) {
  
        res = knitr::knit_child(c(here::here('cor_graphical', 'report_sub1.2.Rmd')), quiet = TRUE)
        cat(res, sep = '\n')
        cat("\\clearpage", sep = '\n')
    }
  }
}
for (strain in c("6_strain")){
  for (panel in set1_panels_2) {
    for (time in set1_times) {
  
        res = knitr::knit_child(c(here::here('cor_graphical', 'report_sub1.3.Rmd')), quiet = TRUE)
        cat(res, sep = '\n')
        cat("\\clearpage", sep = '\n')
    }
  }
}

## Set 2: longitudinal plots #############
for (panel in set2_panels) {
      res = knitr::knit_child(c(here::here('cor_graphical', 'report_sub2.Rmd')), quiet = TRUE)
      cat(res, sep = '\n')
      cat("\\clearpage", sep = '\n')
}
for (panel in set2_panels) {
      res = knitr::knit_child(c(here::here('cor_graphical', 'report_sub2.2.Rmd')), quiet = TRUE)
      cat(res, sep = '\n')
      cat("\\clearpage", sep = '\n')
}
for (panel in set2_panels) {
      res = knitr::knit_child(c(here::here('cor_graphical', 'report_sub2.3.Rmd')), quiet = TRUE)
      cat(res, sep = '\n')
      cat("\\clearpage", sep = '\n')
}
for (time in c("BD1_BD29", "BD1_DeltaBD29overBD1")) {
  for (variant in c("BA.1","D614(G)")) {
      res = knitr::knit_child(c(here::here('cor_graphical', 'report_sub2.4.Rmd')), quiet = TRUE)
      cat(res, sep = '\n')
      cat("\\clearpage", sep = '\n')
  }
}

## Set 3: Correlation plots across markers at a given time point #############
for (time in set3_times) {
  for (strain in c("9_markers", "4_markers")){
      res = knitr::knit_child(c(here::here('cor_graphical', 'report_sub3.Rmd')), quiet = TRUE)
      cat(res, sep = '\n')
      cat("\\clearpage", sep = '\n')
  }
}

for (time in set3_times) {
  for (strain in c("4_markers")){
      res = knitr::knit_child(c(here::here('cor_graphical', 'report_sub3.2.Rmd')), quiet = TRUE)
      cat(res, sep = '\n')
      cat("\\clearpage", sep = '\n')
  }
}

for (time in set3_times) {
  for (strain in c("4_markers")){
      res = knitr::knit_child(c(here::here('cor_graphical', 'report_sub3.3.Rmd')), quiet = TRUE)
      cat(res, sep = '\n')
      cat("\\clearpage", sep = '\n')
  }
}

## Set 4: Correlation plots for a given marker across time points #############
for (assay in assays) {
      res = knitr::knit_child(c(here::here('cor_graphical', 'report_sub4.Rmd')), quiet = TRUE)
      cat(res, sep = '\n')
      cat("\\clearpage", sep = '\n')
}

for (assay in assays) {
      res = knitr::knit_child(c(here::here('cor_graphical', 'report_sub4.2.Rmd')), quiet = TRUE)
      cat(res, sep = '\n')
      cat("\\clearpage", sep = '\n')
}

```
