# Disclaimers


The data presented in the analysis are provided to NIAID in accordance with Clinical Trial Agreement between the parties. The study was funded in part by BARDA under Government Contract No. 75A50120C00034.


\textbf{Statistical Analysis Plan}

The SAP is available at https://doi.org/10.6084/m9.figshare.13198595




```{r, echo=TRUE, results='asis'}

obj.assays=c("bindSpike_BA.1", "pseudoneutid50_BA.1")  
tpeak <- 29
special.note = paste0("$\\ddagger$ Count cases starting 7 days post BD29.")
  
for (iObj in c(1,2)) {
  save.file.label = paste0(study_name,"obj",iObj)
  if (iObj %in% c(1,3)) {
    all.markers = paste0("BD29", obj.assays)
  } else if (iObj==2) {
    all.markers = paste0("DeltaBD29overBD1", obj.assays)
  }
  names(all.markers)=all.markers
  
  if (iObj %in% c(1,2)) {
    COR=glue("Objective {iObj} Naive")
    pathCoRoutput <- paste0("cor_coxph/output/", attr(config,"config"), "/naive")
    res = knitr::knit_child(c(here::here('cor_coxph', 'report_by_COR.Rmd')), quiet = TRUE)
    cat(res, sep = '\n')
    
    COR=glue("Objective {iObj} Non-naive")
    pathCoRoutput <- paste0("cor_coxph/output/", attr(config,"config"), "/nnaive")
    res = knitr::knit_child(c(here::here('cor_coxph', 'report_by_COR.Rmd')), quiet = TRUE)
    cat(res, sep = '\n')
    
  } else if (iObj==3) {
    COR="Objective "%.%iObj
    pathCoRoutput <- paste0("cor_coxph/output/", attr(config,"config"), "/all")
    
    for (a in all.markers) {
      cat(paste0("
      \\begin{table}[H] 
      \\centering
      \\input{",pathCoRoutput,"/CoR_itxn_",a,"}  
      \\caption{ Inference for Day ",tpeak," antibody marker covariate-adjusted correlates of risk by Day \\protect\\input{",pathCoRoutput,"/timepoints_cum_risk_",save.file.label,"} in the vaccine arm. Hazard ratios per 10-fold increment in the marker are shown. ",special.note,"}
      \\end{table}
          "))
    }
    cat("\\clearpage")

  }

}
```


```{r, echo=FALSE, results='asis'}
iObj=3
obj.assays=c("bindSpike_BA.1", "pseudoneutid50_BA.1")  
tpeak <- 29
special.note = paste0("$\\ddagger$ Count cases starting 7 days post BD29.")

save.file.label = paste0(study_name,"obj",iObj)
all.markers = paste0("BD29", obj.assays)
names(all.markers)=all.markers
COR="Objective "%.%iObj
pathCoRoutput <- paste0("cor_coxph/output/", attr(config,"config"), "/all")
cat(glue("# {COR} Univariate CoR: Cox Models of Risk"))

for (a in all.markers) {
  cat(paste0("
  \\begin{table}[H] 
  \\centering
  \\input{",pathCoRoutput,"/CoR_itxn_",a,"}  
  \\caption{ Inference for Day ",tpeak," antibody marker covariate-adjusted correlates of risk by Day \\protect\\input{",pathCoRoutput,"/timepoints_cum_risk_",save.file.label,"} in the vaccine arm. Hazard ratios per 10-fold increment in the marker are shown. ",special.note,"}
  \\end{table}
      ")) }
    cat("\\clearpage")
```
